name: testsuite

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  compile:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Set up JDK 17
      uses: actions/setup-java@v2
      with:
        java-version: '17'
        distribution: 'adopt'
        cache: maven
    - name: Compile with Maven
      run: mvn -B compile --file pom.xml
  unit-tests:
    needs: compile
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Set up JDK 17
      uses: actions/setup-java@v2
      with:
        java-version: '17'
        distribution: 'adopt'
        cache: maven
    - name: Compile with Maven
      run: mvn -B test --file pom.xml
  integration-tests:
    needs: unit-tests
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Set up JDK 17
      uses: actions/setup-java@v2
      with:
        java-version: '17'
        distribution: 'adopt'
        cache: maven
    - name: Compile with Maven
      run: mvn -B verify -Prun-its --file pom.xml
